server:
  port: 8088
  servlet:
    context-path: "/sun"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/communit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aaa123+-*/
    maxActive: 20
    initialSize: 1
    maxWait: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl